---
- name: Install from package
  when: helm_install_with_package
  block:
    - name: Get apt key
      become: true
      ansible.builtin.get_url:
        url: https://baltocdn.com/helm/signing.asc
        dest: /usr/share/keyrings/helm.asc
        mode: '0644'
        owner: root
        group: root

    - name: Add Helm apt repository
      become: true
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ _helm_arch_mapping[ansible_facts.architecture] }}
          signed-by=/usr/share/keyrings/helm.asc] https://baltocdn.com/helm/stable/debian/ all main"
        state: present
        filename: helm-stable-debian
        update_cache: true

    - name: Install Helm
      become: true
      ansible.builtin.apt:
        name: helm
        state: present

- name: Install from archive
  when: not helm_install_with_package
  ansible.builtin.include_tasks: setup/default.yml

...
